import type {Metadata} from "next";
import {Poppins} from "next/font/google";
import "./globals.css";
import {Navbar} from "../ui/Navbar/Navbar";

const poppins = Poppins({subsets: ["latin"], weight: ["200", "400", "600"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        {children}
        <footer>Stuff at the bottom</footer>
      </body>
    </html>
  );
}
